### ISSUE TITLE
About the crop_pic.py file

### ISSUE THREAD

**Issue by zrqi** [D-X-Y/SAN#10]
I am very puzzled when using crop_pic.py file to cut images, which function is mainly called for image face cutting in the py file？Is it the ' __call__()' under the PreCrop?

**Comment by D-X-Y** [comment]
Yes, the cropping operation is in here https://github.com/D-X-Y/SAN/blob/master/lib/san_vision/transforms.py#L202 ; It is used to crop the face based on the face bounding box with extension.
