### ISSUE TITLE
How to get the style-aggregated img from the style-aggregated face generation module

### ISSUE THREAD

**Issue by zhouling0922** [D-X-Y/SAN#12]
Excuse me, sorry to disturb you！
I have used your pre-trained model to get  the 68 landmarks of the test.img.
But if I want to get the face img( i want to save the new face img on my disk) which aggregated from the style-aggregated face generation module, how can i do, thank you.

**Comment by D-X-Y** [comment]
Please refer to this code : https://github.com/D-X-Y/SAN/blob/master/lib/procedure/train_detector.py#L118 `generated` is the style-aggregated faces. And you can find the visualization results by this line `https://github.com/D-X-Y/SAN/blob/master/lib/procedure/train_detector.py#L155`, if you set the debug_save arg.

**Comment by zhouling0922** [comment]
Thanks for your rapidly reply and sorry to disturb you again.
I tried to use your released pre_trained model to run the test_1.jpg and want to get the intermediate result of this img( the aggregated-style img of test_1.jpg) but the train() function in the train_detector.py will never be runned.
So, if is it possible for me to get the aggregated-style of the test_1.jpg with your pre-trained module, Thank you?

**Comment by D-X-Y** [comment]
Yes, but you need to modify the code, see `https://github.com/D-X-Y/SAN/blob/master/lib/models/itn_cpm.py#L141` the outputs contain the aggregated-style image, and it equals to `_` in https://github.com/D-X-Y/SAN/blob/master/san_eval.py#L55. You can visualize the `_` variable, which is aggregated-style image

**Comment by zhouling0922** [comment]
Thank you so much, I will try it right away.
