### ISSUE TITLE
something wrong when using crop_pic.py

### ISSUE THREAD

**Issue by husencd** [D-X-Y/SAN#13]
Hello! I generate lists successfully. But when I crop face using crop_pic.py, I met a problem.
As for 300W, it cropped 3636 faces totally, not 3837.
As for AFLW, it cropped 21123 faces totally, not 24386.
Could you please tell me why the numbers are not equal?

**Comment by D-X-Y** [comment]
Sorry for the late reply!
It might be because that some faces are cropped from the same image (one image may have different faces), and after cropping, these faces in the same image might be saved as the same name. This is just my guess, I will check this after CVPR.
