### ISSUE TITLE
Evaluation. 

### ISSUE THREAD

**Issue by CHELSEA234** [D-X-Y/SAN#18]
https://github.com/D-X-Y/SAN/issues/17#issuecomment-455752700

**Comment by cmburgul** [comment]
@CHELSEA234 Did you fixed the problem of bounding box for images other than 300W dataset. As Mentioned in #14 other bounding box is not giving good results. Did you got any success ?

**Comment by cmburgul** [comment]
@CHELSEA234 
The facial bounding box format followed by 300W dataset is ( top-left x, top-left y, bottom right x, bottom right y). The other formats like MTCNN follows (top-left x, top-left y, width, height). I took a out of dataset image and used MTCNN to detect bounding box and changed the format and I am getting facial landmarks ish accurate.
