### ISSUE TITLE
evaluate other picture

### ISSUE THREAD

**Issue by cploveflower** [D-X-Y/SAN#23]
when I make an evaluation on other picture (the picture belongs to 300W) ,I found the landmark is not accurate,when I use my own dataset,I found it has the same problem,can you help me solve it or give me any other suggestion?thank you

**Comment by D-X-Y** [comment]
Did you follow the readme at https://github.com/D-X-Y/SAN#evaluation-on-the-single-image ?

**Comment by D-X-Y** [comment]
Close the issues as it is inactive for about one week.

**Comment by cmburgul** [comment]
The facial bounding box format followed by 300W dataset is ( top-left x, top-left y, bottom right x, bottom right y). The other formats like MTCNN follows (top-left x, top-left y, width, height). I took a out of dataset image and used MTCNN to detect bounding box and changed the format and I am getting facial landmarks ish accurate.
