### ISSUE TITLE
Can you also provide a test script? 

### ISSUE THREAD

**Issue by qingguoxu** [D-X-Y/SAN#6]
Hi Xuanyi, thanks for your great work. I'm trying to test your network on our dataset for facial landmarks detection. I follow your steps and finish the training and evaluation step. I want to just test on a few subjects. So it would be great that you can also share a simple test script. Like for a new coming image, it can detect the 68 landmarks. Thanks.

**Comment by Edwardmark** [comment]
upvote

**Comment by D-X-Y** [comment]
Sure, I will update this before CVPR 2018.

**Comment by D-X-Y** [comment]
@qingguoxu @Edwardmark hi, I have add the evaluation script for a single image, see https://github.com/D-X-Y/SAN#evaluation-on-the-single-image

Best Regards,

**Comment by qingguoxu** [comment]
@D-X-Y ， Thanks so much.
