### ISSUE TITLE
Run test script error

### ISSUE THREAD

**Issue by darengking** [D-X-Y/SAN#8]
Hi，Xuanyi
       I download the Pretrained model from google drive, but when I run the test script 'CUDA_VISIBLE_DEVICES=1 python san_eval.py --image ./cache_data/cache/test_1.jpg --model ./snapshots/SAN_300W_GTB_itn_cpm_3_50_sigma4_128x128x8/checkpoint_49.pth.tar --face 819.27 432.15 971.70 575.87'  I got the error message:

The image is ./cache_data/cache/test_1.jpg
The model is ./snapshots/checkpoint_49.pth.tar
The face bounding box is [819.27, 432.15, 971.7, 575.87]
Traceback (most recent call last):
  File "san_eval.py", line 78, in <module>
    evaluate(args)
  File "san_eval.py", line 32, in evaluate
    snapshot = torch.load(snapshot)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 304, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 460, in _load
    magic_number = pickle_module.load(f)
TypeError: argument must have 'read' and 'readline' attributes
Do you have any idea?

**Comment by D-X-Y** [comment]
could you provide the python version and the pytorch version that you use?

**Comment by darengking** [comment]
I use python2.7 and pytorch0.4.0. I just see the Dependencies needs python3.6, is that the reason?

**Comment by D-X-Y** [comment]
Yes, I think so. You could use python3.6 and try again~

**Comment by darengking** [comment]
@D-X-Y I will try, thank you~
