### ISSUE TITLE
I can't download the datasets of 300w-style and AFLW-style

### ISSUE THREAD

**Issue by zrqi** [D-X-Y/SAN#9]
Hi,I'm interested in your algorithm, so I'd like to try the implementation of the algorithm, but I can't download the dataset, could you send the datasets to my mailbox ?Thank you(●'◡'●)

**Comment by D-X-Y** [comment]
Sure, please provide your email.

**Comment by zrqi** [comment]
531373199@qq.com  thank you so much～

**Comment by zrqi** [comment]
531373199@qq.com  thank you so much～

**Comment by lisha-chen** [comment]
Hi, I am interested in the SAN algorithm and the dataset 300W-style and AFLW-style. But I cannot find the dataset, can you send me the dataset? Thank you. My email is lishachen00@gmail.com

**Comment by D-X-Y** [comment]
@lisha-chen Can you download these two datasets from https://drive.google.com/open?id=14f2lcJVF6E4kIICd8icUs8UuF3J0Mutd ? The names are AFLW-Style.tgz and 300W-Style.tgz.
